services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: demo_credit
      MYSQL_USER: demo_credit
      MYSQL_PASSWORD: demo_credit_local
      MYSQL_ROOT_PASSWORD: root_local_only
    ports: ['3306:3306']
    volumes: [demo-credit-mysql:/var/lib/mysql]
    healthcheck:
      {
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-proot_local_only'],
        interval: 5s,
        timeout: 3s,
        retries: 20,
      }
volumes: { demo-credit-mysql: {} }
